module.exports = {
  projects: [
    '<rootDir>/apps/demo-angular-web',
    '<rootDir>/apps/demo-api',
    '<rootDir>/libs/demo-api/sensors/api',
    '<rootDir>/libs/demo-api/sensors/interfaces',
    '<rootDir>/libs/demo-api/sensors/fixtures',
    '<rootDir>/libs/demo-angular/sensors/feature-shell',
    '<rootDir>/libs/shared/sensors/data-access',
    '<rootDir>/libs/shared/sensors/ui',
    '<rootDir>/libs/shared/api/core',
    '<rootDir>/libs/shared/api/interfaces',
    '<rootDir>/libs/demo-angular/sensors/feature-sensor-details',
    '<rootDir>/libs/shared/custom-router/data-access',
    '<rootDir>/libs/shared/core',
    '<rootDir>/libs/shared/util/typescript',
    '<rootDir>/libs/demo-angular/sensors/feature-sensor-overview',
    '<rootDir>/libs/shared/util/pagination',
    '<rootDir>/libs/demo-angular/sensors/util',
    '<rootDir>/libs/shared/sensors/feature-sensor-list',
    '<rootDir>/libs/shared/sensors/feature-sensor-info',
    '<rootDir>/libs/shared/ui/card',
    '<rootDir>/libs/shared/ui/navbar',
    '<rootDir>/libs/shared/ui/storybook',
  ],
};
